# Generated by iptables-save v1.8.10 (nf_tables) on Mon May 25 11:08:29 2026
*filter
:INPUT ACCEPT [89:6311]
:FORWARD ACCEPT [11:724]
:OUTPUT ACCEPT [353:42809]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -p icmp -j DROP
-A FORWARD -s 10.0.2.2/32 -d 172.16.1.11/32 -p tcp -m tcp --dport 22 -j ACCEPT
-A FORWARD -d 172.16.1.10/32 -p tcp -m tcp --dport 80 -j ACCEPT
-A FORWARD -d 172.16.1.10/32 -p tcp -m tcp --dport 443 -j ACCEPT
-A FORWARD -d 172.16.1.0/24 -j DROP
COMMIT
# Completed on Mon May 25 11:08:29 2026
# Generated by iptables-save v1.8.10 (nf_tables) on Mon May 25 11:08:29 2026
*nat
:PREROUTING ACCEPT [15:1964]
:INPUT ACCEPT [2:88]
:OUTPUT ACCEPT [59:4311]
:POSTROUTING ACCEPT [46:3312]
-A POSTROUTING -o enp0s3 -j MASQUERADE
COMMIT
# Completed on Mon May 25 11:08:29 2026
